apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app.kubernetes.io/name: producer
    app.kubernetes.io/instance: producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: producer
      app.kubernetes.io/instance: producer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: producer
        app.kubernetes.io/instance: producer
    spec:
      containers:
        - name: producer  
          image: "pavelmikhalchuk/kafka-producer:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP