---
# Source: kafdrop/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  labels:
    app.kubernetes.io/name: kafdrop
    helm.sh/chart: kafdrop-0.1.0
    app.kubernetes.io/instance: kafdrop
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 
  selector:
    app.kubernetes.io/name: kafdrop
    app.kubernetes.io/instance: kafdrop
