---
# Source: kafka-manager/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kafka-manager
  labels:
    app.kubernetes.io/instance: kafka-manager
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kafka-manager
    app.kubernetes.io/version: 1.3.3.22
    helm.sh/chart: kafka-manager-2.2.0
type: Opaque
data:
  
  applicationSecret: "ZUV4RjFTbHNOQg=="
  
  basicAuthUsername:  "YWRtaW4="
  
  basicAuthPassword: "STFZeFVuUllCSg=="
  
