---
# Source: kafka-manager/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: kafka-manager
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kafka-manager
    app.kubernetes.io/version: 1.3.3.22
    helm.sh/chart: kafka-manager-2.2.0
  name: kafka-manager
