---
# Source: kafka-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  labels:
    app.kubernetes.io/instance: kafka-manager
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kafka-manager
    app.kubernetes.io/version: 1.3.3.22
    helm.sh/chart: kafka-manager-2.2.0
spec:
  type: ClusterIP
  ports:
    - name: kafka-manager
      port: 9000
      targetPort: kafka-manager
      protocol: TCP
  selector:
    app: kafka-manager
    release: kafka-manager
