topic:
  name: avro-clicks
  partitions-num: 6
  replication-factor: 3

spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://kafka-cp-schema-registry.kafka:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"