apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app.kubernetes.io/name: consumer
    app.kubernetes.io/instance: consumer
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: consumer
      app.kubernetes.io/instance: consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: consumer
        app.kubernetes.io/instance: consumer
    spec:
      containers:
        - name: consumer  
          image: "pavelmikhalchuk/kafka-consumer:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP