---
# Source: cp-schema-registry/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-cp-schema-registry
  labels:
    app: cp-schema-registry
    chart: cp-schema-registry-0.1.0
    release: kafka
    heritage: Tiller
spec:
  ports:
    - name: schema-registry
      port: 8081
  selector:
    app: cp-schema-registry
    release: kafka
