apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/pavel-mikhalchuk/kafka-playground.git
    targetRevision: HEAD
    path: infra/state/kafka
    directory: 
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
